import type { ChatMessage } from './ai'

/**
 * AI paper brief: prompt building and draft merging, all pure.
 *
 * Boundaries baked in here, not left to prompting alone:
 * - the model sees ONLY metadata + abstract and is told to hedge — a brief of
 *   an unread paper is labeled summarization of the authors' claims;
 * - `mergeBrief` structurally cannot touch frontmatter or 我的评价 — the
 *   owner's judgment is the KB's actual value and stays human;
 * - generated sections carry a visible marker, and rerunning replaces the
 *   marked block instead of stacking drafts.
 */

export interface BriefInput {
  title: string
  authors: string[]
  venue: string
  year: number
  abstract: string | null
}

export const AI_DRAFT_MARKER = '<!-- AI 初稿（基于摘要生成），待核对 -->'

export function buildBriefPrompt(p: BriefInput): { system: string; messages: ChatMessage[] } {
  const system = [
    '你是一名图形学/计算机方向的中文论文导读助手。',
    '只依据给定的元数据与摘要写导读，绝不编造摘要之外的数字、实验结果或结论；不确定之处标注「（待核对）」。',
    p.abstract === null
      ? '注意：本次没有摘要，只有标题与出处。只能做非常保守的推测，每一条都必须带「（待核对）」。'
      : '',
    '输出格式：只输出两节——`## 贡献`（编号列表，每条一句话）和 `## 方法`（要点式段落）。',
    '不要输出 frontmatter、标题行、其他小节或任何评价性内容。用简体中文，专业术语首次出现时在括号里标注英文。',
  ]
    .filter(Boolean)
    .join('\n')

  const user = [
    `标题：${p.title}`,
    `作者：${p.authors.join(', ')}`,
    `发表：${p.venue} ${p.year}`,
    '',
    p.abstract === null ? '（无摘要）' : `摘要：\n${p.abstract}`,
    '',
    '请生成导读。',
  ].join('\n')

  return { system, messages: [{ role: 'user', content: user }] }
}

/**
 * Reads what the brief needs out of a to-read placeholder's frontmatter with
 * line regexes — the frontmatter is machine-generated by import-bibtex.ts
 * with known shapes, so a YAML parser (and its Buffer polyfill baggage) is
 * not worth shipping to the browser. Returns null when the text doesn't look
 * like a paper page.
 */
export function parseBriefMeta(
  md: string,
): (BriefInput & { doi?: string; arxiv?: string }) | null {
  const fm = md.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1]
  if (!fm) return null

  const line = (key: string) => fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))?.[1]?.trim()
  const unquote = (s: string | undefined) =>
    s?.replace(/^['"]/, '').replace(/['"]$/, '').trim() || undefined

  const title = unquote(line('title'))
  if (!title) return null

  // authors: either inline ["a", "b"] or a block list of "  - name" lines.
  let authors: string[] = []
  const inline = fm.match(/^authors:\s*\[([\s\S]*?)\]/m)?.[1]
  if (inline) {
    authors = inline
      .split(',')
      .map((a) => unquote(a.trim()) ?? '')
      .filter(Boolean)
  } else {
    const block = fm.match(/^authors:\s*\r?\n((?:\s+-\s+.*\r?\n?)+)/m)?.[1]
    if (block) {
      authors = block
        .split(/\r?\n/)
        .map((l) => unquote(l.replace(/^\s+-\s+/, '').trim()) ?? '')
        .filter(Boolean)
    }
  }

  return {
    title,
    authors,
    venue: unquote(line('venue')) ?? '',
    year: Number(line('year')) || 0,
    abstract: null,
    doi: unquote(line('doi')),
    arxiv: unquote(line('arxiv')),
  }
}

/**
 * Merges the model's 贡献/方法 sections into the placeholder markdown.
 * Frontmatter is copied through verbatim; 我的评价 and the import comment
 * are never touched. A target section is only replaced when it is empty or
 * begins with the AI draft marker (so a rerun replaces, never duplicates);
 * any human text refuses the merge.
 */
export function mergeBrief(
  existing: string,
  brief: string,
): { ok: true; text: string } | { ok: false; message: string } {
  const generated = extractSections(brief)
  if (!generated['贡献'] || !generated['方法']) {
    return { ok: false, message: 'AI 输出缺少 ## 贡献 或 ## 方法 小节，未合并' }
  }

  const fmMatch = existing.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/)
  const frontmatter = fmMatch?.[0] ?? ''
  let body = existing.slice(frontmatter.length)

  for (const name of ['贡献', '方法'] as const) {
    const re = new RegExp(`(^## ${name}[ \\t]*\\r?\\n)([\\s\\S]*?)(?=^## |(?![\\s\\S]))`, 'm')
    const m = body.match(re)
    if (!m) return { ok: false, message: `占位页里找不到 ## ${name} 小节，未合并` }
    const current = m[2].trim()
    if (current !== '' && !current.startsWith(AI_DRAFT_MARKER)) {
      return { ok: false, message: `## ${name} 已有人工内容，不覆盖` }
    }
    const replacement = `${m[1]}\n${AI_DRAFT_MARKER}\n\n${generated[name].trim()}\n\n`
    body = body.replace(re, replacement.replace(/\$/g, '$$$$'))
  }

  return { ok: true, text: frontmatter + body }
}

/** `## 标题` → body text, for the model output only (flat structure). */
function extractSections(md: string): Record<string, string> {
  const out: Record<string, string> = {}
  const re = /^## +(\S[^\n]*?)[ \t]*\r?\n([\s\S]*?)(?=^## |(?![\s\S]))/gm
  for (const m of md.matchAll(re) as Iterable<RegExpMatchArray>) {
    out[m[1].trim()] = m[2].trim()
  }
  return out
}
